DEFAULT_VARIANTS = {
    "crypto_lag_conservative": {
        "strategy_name": "crypto_lag",
        "variant_name": "crypto_lag_conservative",
        "enabled": True,
        "min_edge": 0.01,
        "max_spread": 0.10,
        "min_hours": 1.0,
        "max_hours": 24.0,
        "size_multiplier": 1.00,
        "exposure_multiplier": 1.00,
        "cooldown_seconds": 300,
        "take_profit": 0.12,
        "stop_loss": -0.08,
        "max_hold_hours": 10.0,
        "force_exit_near_expiry_hours": 0.25,
    },
    "crypto_lag_adaptive": {
        "strategy_name": "crypto_lag",
        "variant_name": "crypto_lag_adaptive",
        "enabled": True,
        "min_edge": 0.015,
        "max_spread": 0.12,
        "min_hours": 1.0,
        "max_hours": 24.0,
        "size_multiplier": 0.75,
        "exposure_multiplier": 0.75,
        "cooldown_seconds": 450,
        "take_profit": 0.15,
        "stop_loss": -0.10,
        "max_hold_hours": 8.0,
        "force_exit_near_expiry_hours": 0.25,
    },
    "crypto_lag_aggressive": {
        "strategy_name": "crypto_lag",
        "variant_name": "crypto_lag_aggressive",
        "enabled": True,
        "min_edge": 0.02,
        "max_spread": 0.14,
        "min_hours": 1.0,
        "max_hours": 24.0,
        "size_multiplier": 0.50,
        "exposure_multiplier": 0.50,
        "cooldown_seconds": 600,
        "take_profit": 0.18,
        "stop_loss": -0.12,
        "max_hold_hours": 6.0,
        "force_exit_near_expiry_hours": 0.25,
    },
}
